-- CalmSense - Supabase schema
-- Run this once in your Supabase project: Dashboard -> SQL Editor -> New query
-- -> paste -> Run.
--
-- Columns mirror the JSON record written by the backend (models.SensorData):
--   user_id, panic_attack_detection, current_hr, current_hrv,
--   current_motion_intensity, timestamp.
-- "id" and "created_at" are added by the DB; the backend never sends them.

create table if not exists public.sensor_data (
    id                       bigint generated always as identity primary key,
    user_id                  text        not null,
    panic_attack_detection   boolean     not null,
    current_hr               double precision,
    current_hrv              double precision,
    current_motion_intensity double precision,
    timestamp                timestamptz,
    created_at               timestamptz not null default now()
);

-- Query sensor history per user quickly.
create index if not exists sensor_data_user_id_idx
    on public.sensor_data (user_id);

-- Labeled training signals from the user. Used to retrain the panic
-- classifier and to track model hit/miss rate per user.
create table if not exists public.panic_feedback (
    id                        bigint generated always as identity primary key,
    user_id                   text        not null,
    was_panic                 boolean     not null,
    severity                  smallint    check (severity between 1 and 10),
    detected_by_model         boolean     not null,
    current_hr                double precision,
    current_hrv               double precision,
    current_motion_intensity  double precision,
    model_probability         double precision,
    timestamp                 timestamptz,
    created_at                timestamptz not null default now()
);

create index if not exists panic_feedback_user_id_idx
    on public.panic_feedback (user_id);

-- Journaled panic-attack reports filled in by the user post-event. Used for
-- pattern tracking and to review with a therapist. Free-text columns and
-- GPS are sensitive — keep server-side access on the service_role key only.
create table if not exists public.panic_reports (
    id                        bigint generated always as identity primary key,
    user_id                   text        not null,
    timestamp                 timestamptz,
    severity                  smallint    not null check (severity between 1 and 10),
    detected_by_model         boolean     not null,
    feeling                   text,
    symptoms                  jsonb,
    activity_before           text,
    what_helped               text,
    duration_minutes          integer     check (duration_minutes between 0 and 1440),
    latitude                  double precision,
    longitude                 double precision,
    location_accuracy_m       double precision,
    current_hr                double precision,
    current_hrv               double precision,
    current_motion_intensity  double precision,
    created_at                timestamptz not null default now()
);

create index if not exists panic_reports_user_id_idx
    on public.panic_reports (user_id);
create index if not exists panic_reports_timestamp_idx
    on public.panic_reports ("timestamp");

-- ===========================================================================
-- Admin + model-versioning tables.
--
-- storage.py has always referenced these (admin_users, model_weights,
-- user_model_state) but they were missing from this file, because the stack
-- had only ever run on the JSON fallback where tables are implicit. Without
-- them the admin dashboard cannot log in and no retrain/rollback can be saved.
--
-- Unlike the tables above these use GENERATED BY DEFAULT AS IDENTITY, so a
-- migration can insert explicit ids. That is required, not cosmetic:
-- user_model_state.active_weights_id points at model_weights.id, so those ids
-- have to survive the move from the JSON store.
-- ===========================================================================

create table if not exists public.admin_users (
    id            bigint      generated by default as identity primary key,
    email         text        not null unique,
    name          text,
    password_hash text        not null,
    is_active     boolean     not null default true,
    created_at    timestamptz not null default now()
);

create table if not exists public.model_weights (
    id               bigint      generated by default as identity primary key,
    user_id          text        not null,
    weights          jsonb       not null,
    feature_names    jsonb,
    model_type       text,
    test_accuracy    double precision,
    training_samples integer,
    trained_through  text,
    source           text,
    note             text,
    created_at       timestamptz not null default now()
);

-- list_model_snapshots() filters by user_id and orders by created_at desc.
create index if not exists model_weights_user_created_idx
    on public.model_weights (user_id, created_at desc);

-- user_id is the PRIMARY KEY because storage.upsert_user_model_state() calls
-- upsert(..., on_conflict="user_id"), which needs a unique constraint on it.
create table if not exists public.user_model_state (
    user_id           text        primary key,
    active_weights_id bigint      references public.model_weights (id) on delete set null,
    training_cutoff   text,
    updated_at        timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Row Level Security
--
-- Enabled on every table with NO policies, which denies everything to the anon
-- and authenticated roles. The backend is unaffected: it connects with the
-- service_role key, which bypasses RLS by design.
--
-- The original note below said policies "are not required", which was true
-- while the API was reachable only over the private tailnet. Now that it is
-- published on the internet, defence in depth is cheap: if the anon key ever
-- leaks, it still yields nothing. These tables hold heart-rate history, panic
-- journals and GPS coordinates.
--
-- If you ever let the Android app talk to Supabase directly, you must ADD
-- explicit per-user policies first — enabling RLS alone will just block it.
-- ---------------------------------------------------------------------------
alter table public.sensor_data      enable row level security;
alter table public.panic_feedback   enable row level security;
alter table public.panic_reports    enable row level security;
alter table public.admin_users      enable row level security;
alter table public.model_weights    enable row level security;
alter table public.user_model_state enable row level security;
