-- Only needed if migrate_json_to_supabase.py was run with --preserve-ids.
--
-- The default path lets Postgres assign ids and remaps the one foreign key
-- (user_model_state.active_weights_id) in Python, so the identity sequences
-- stay correct on their own and this file can be ignored entirely.
--
-- With --preserve-ids the rows carry explicit ids, which does NOT advance the
-- sequence behind a `generated by default as identity` column. The next insert
-- would then reuse an id that already exists and fail with a duplicate key --
-- typically surfacing much later, the first time someone retrains a model.
--
-- Run this in the Supabase SQL editor (supabase-py cannot execute raw SQL),
-- then re-run the migration's --verify to confirm the identity probe passes.

-- The third argument to setval is is_called. Passing false when the table is
-- empty avoids "setval: value 0 is out of bounds", and passing true otherwise
-- means the next value is max(id)+1 rather than max(id).
select setval(
    pg_get_serial_sequence('public.model_weights', 'id'),
    coalesce((select max(id) from public.model_weights), 1),
    (select max(id) is not null from public.model_weights)
);

select setval(
    pg_get_serial_sequence('public.admin_users', 'id'),
    coalesce((select max(id) from public.admin_users), 1),
    (select max(id) is not null from public.admin_users)
);

-- Expect each to report a value >= the table's max(id).
select 'model_weights' as t, max(id) as max_id,
       pg_get_serial_sequence('public.model_weights', 'id') as seq
from public.model_weights
union all
select 'admin_users', max(id), pg_get_serial_sequence('public.admin_users', 'id')
from public.admin_users;
